### PR TITLE
chore: add 'source' and 'target' inputs

### PR DESCRIPTION
**Pull request by PascalBrouwers**

### CODE REVIEW

**Comment by PascalBrouwers** [comment]
This fixes:
```
Unexpected input(s) 'source', 'target', valid inputs are ['entryPoint', 'args', 'host', 'port', 'passphrase', 'username', 'password', 'sync', 'use_insecure_cipher', 'cipher', 'timeout', 'command_timeout', 'key', 'key_path', 'fingerprint', 'proxy_host', 'proxy_port', 'proxy_username', 'proxy_password', 'proxy_passphrase', 'proxy_timeout', 'proxy_key', 'proxy_key_path', 'proxy_fingerprint', 'proxy_cipher', 'proxy_use_insecure_cipher', 'script', 'script_stop', 'envs', 'debug']
```
Because 'source' and 'target' are valid inputs

**Comment by PascalBrouwers** [comment]
@appleboy can you add this to the `master` branch?

**Comment by appleboy** [comment]
@PascalBrouwers I will take it. Why need the two variables?

**Comment by appleboy** [comment]
ssh-action doesn't support `source` and `target` parameters. Thanks.

**Comment by PascalBrouwers** [comment]
I need it to upload a file to the server

**Comment by appleboy** [comment]
@PascalBrouwers Please try [scp-action](https://github.com/appleboy/scp-action)

**Comment by appleboy** [comment]
@PascalBrouwers This issue has been closed 3 days ago

**Pull request closed without merging**
