### PR TITLE
Update Dockerfile

### PR DESCRIPTION
**Pull request by agkaran**

### CODE REVIEW

**Comment by agkaran** [comment]
getting an error --> manifest for appleboy/drone-ssh:1.6.5-linux-amd64 not found: manifest unknown: manifest unknown

**Review by jamal-io — APPROVED** [review]

**Comment by larrrssss** [comment]
Looks like a failed pipline on the mentioned plugin https://github.com/appleboy/drone-ssh/commit/5525ed602fe212de9d5e584befe54f2410a4468b cause this issue. Best way to prevent these types of errors is to use the latest release in your configuration file (`appleboy/ssh-action@v0.1.5`).

**Comment by appleboy** [comment]
update in the master branch. I will bump the new version.

**Comment by jamal-hex** [comment]
Thank you!

**Pull request closed without merging**
